#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times using while loop with if
i="0"

while ((i < 10)); do
    if (( i==9)); then
	echo "Hi"
    fi
    echo "Holberton School"
     ((i++))
done
