#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times using while loop with if
h="0"

while ((h <= 12)); do
    echo "Hour:" $h
    m=1
    while (( m <= 59)); do
	echo $m
	((m++))
    done
    ((h++))
done
