#!/usr/bin/env bash
# bash script to nginx on server
sudo apt-get upgrade && sudo apt-get install -y nginx

#Change index.html to read "Holberton School"
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
