#!/usr/bin/env bash
# bash script to nginx on server
sudo apt-get -y upgrade && sudo apt-get install -y nginx

#Change index.html to read "Holberton School"
echo "Holberton School" > /usr/share/nginx/html/index.html
service nginx restart
